
language: python

python:
  - { PATH: "{{replace(Python37, '\\', '\\\\')}}", VERSION: 3.7, DIST: std }
  
virtualenv:
  - path: {{ospathjoin(root_path, pickname("%NAME_JENKINS%", project_name + "_%VERSION%_%DIST%_%NAME%"), "_venv")}}
  
install:
  - pip install --no-cache-dir --no-deps --index http://localhost:8067/simple/ pyquickhelper pyensae pymmails pymyinstall pyrsslocal ensae_projects
  - pip install -r requirements.txt
  # no cuda
  - pip uninstall cupy
  - pip freeze
  - pip freeze > pip_freeze.txt  
script:
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests -g \".*((noenv)|(LONG)|(SKIP)).*\"", NAME: "UT" }
  - { CMD: "python -u setup.py unittests -e \".*noenv1.*\" -g .*LONG.*", NAME: "UT_NOENV1" }
  - { CMD: "python -u setup.py unittests -e \".*noenv2.*\"", NAME: "UT_NOENV2" }
  - { CMD: "python -u setup.py unittests -e \".*noenv3.*\"", NAME: "UT_NOENV3" }
  - { CMD: "python -u setup.py unittests -e \".*noenv4.*\"", NAME: "UT_NOENV4" }
  - { CMD: "python -u setup.py unittests -e \".*noenv5.*\"", NAME: "UT_NOENV5" }
  - { CMD: "python -u setup.py unittests -e \".*noenv6.*\"", NAME: "UT_NOENV6" }
  - { CMD: "python -u setup.py unittests -e \".*noenv7.*\"", NAME: "UT_NOENV7" }
  - { CMD: "python -u setup.py unittests -e \".*noenv8.*\"", NAME: "UT_NOENV8" }
  - { CMD: "python -u setup.py unittests -e \".*noenv9.*\"", NAME: "UT_NOENV9" }
  - { CMD: "python -u setup.py unittests -e \".*noenvA.*\"", NAME: "UT_NOENVA" }
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests -e .*LONG.* -g .*youtube.*", NAME: "UT_LONG" }
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests -e .*youtube.*", NAME: "UT_YOUTUBE" }
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests_SKIP", NAME: "UT_SKIP" }
after_script:
  - python -u setup.py bdist_wheel
  - if [ ${DIST} != "conda" and ${NAME} == "UT" ] then copy dist\*.whl {{root_path}}\..\..\local_pypi\local_pypi_server fi
documentation:
  - if [ ${NAME} == "UT" ] then python -u setup.py build_sphinx fi
  - if [ ${NAME} == "UT" ] then xcopy /E /C /I /Y _doc\sphinxdoc\build\html dist\html fi
  - if [ ${NAME} == "UT" ] then xcopy /E /C /I /Y _doc\sphinxdoc\build\elatex\*.pdf dist\html fi
