
language: python

python:
  - { PATH: "{{Python39}}", VERSION: 3.9, DIST: std, PYINT: python3.9, PYTHONPATH: src }
  
virtualenv:
  - path: {{ospathjoin(root_path, pickname("$NAME_JENKINS", project_name + "_$VERSION_$DIST_$NAME"), "_venv")}}
  
install:
  - $PYINT -m pip install --upgrade pip
  - $PYINT -m pip install --no-cache-dir --upgrade --no-deps --index http://localhost:8067/simple/ pyquickhelper pyensae pymmails pymyinstall pyrsslocal ensae_projects jyquickhelper --extra-index-url=https://pypi.python.org/simple/
  - $PYINT -m pip install -r requirements.txt
  - $PYINT -m pip install shapely==1.6.4
  - $PYINT --version
  - $PYINT -m pip freeze

script:
  - { CMD: "$PYINT -u setup.py unittests -g \".*((noenv)|(LONG)|(SKIP)).*\"", NAME: "UT" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*noenv1.*\" -g .*LONG.*", NAME: "UT_NOENV1", SCHEDULER: "H H(1-2) 23 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*noenv2.*\"", NAME: "UT_NOENV2", SCHEDULER: "H H(1-2) 19 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*noenv3.*\"", NAME: "UT_NOENV3", SCHEDULER: "H H(1-2) 23 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*noenv4.*\"", NAME: "UT_NOENV4", SCHEDULER: "H H(1-2) 23 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*noenv5.*\"", NAME: "UT_NOENV5", SCHEDULER: "H H(1-2) 23 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*noenv6.*\"", NAME: "UT_NOENV6", SCHEDULER: "H H(1-2) 23 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*noenv7.*\"", NAME: "UT_NOENV7", SCHEDULER: "H H(1-2) 23 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*noenv8.*\"", NAME: "UT_NOENV8", SCHEDULER: "H H(1-2) 23 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*noenv9.*\"", NAME: "UT_NOENV9", SCHEDULER: "H H(1-2) 23 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*noenvA.*\"", NAME: "UT_NOENVA", SCHEDULER: "H H(1-2) 23 * *" }
  - { CMD: "$PYINT -X faulthandler -X showrefcount -u setup.py unittests -e \".*scratch.*\" -g \".*youtube.*\"", NAME: "UT_SCRATCH", SCHEDULER: "H H(1-2) 23 * *" }
  - { CMD: "$PYINT -X faulthandler -X showrefcount -u setup.py unittests -e \".*youtube.*\"", NAME: "UT_YOUTUBE", SCHEDULER: "H H(1-2) 23 * *" }
  - { CMD: "$PYINT -u setup.py unittests_SKIP", NAME: "UT_SKIP", SCHEDULER: "H H(1-2) 23 * *" }

after_script:
  - $PYINT -u setup.py bdist_wheel
  - if [ ${VERSION} == "3.9" and ${DIST} != "conda" and ${NAME} == "UT" ] then cp dist/*.whl {{root_path}}/../local_pypi/local_pypi_server fi

documentation:
  - if [ ${NAME} == "UT" ] then $PYINT -u setup.py build_sphinx --layout=html,pdf fi
  - if [ ${NAME} == "UT" ] then cp -R -f _doc/sphinxdoc/build/html dist/html fi
  - if [ ${NAME} == "UT" ] then cp -R -f _doc/sphinxdoc/build/elatex/*.pdf dist/html fi
