language: python
python:
  - "3.4"
install:
  - sudo apt-get update
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION cvxopt scipy h5py scikit-learn
  - pip install -r requirements.txt
  #- source activate test-environment
  - python setup.py install
script:
  - python setup.py unittests
