language: python
python:
    - "3.5"
install: 
    - pip install -r requirements.txt
    - pip install -U git+https://github.com/quantopian/qgrid --no-deps
    - pip install -r requirements_ext.txt
script:
    - python setup.py unittests
