image:
  - Visual Studio 2019
environment:
  matrix:
    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9.x"
      PYTHON_ARCH: "64"
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install pymyinstall"
  - "%PYTHON%\\Scripts\\pymy_install3 pyproj cartopy cairocffi shapely llvmlite numba"
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt"
  - set PYTHONPATH=src
  
build: off

test_script:
  - "%PYTHON%\\python -u setup.py unittests -g \".*((noenv)|(LONG)).*\""

after_test:
  - "%PYTHON%\\python -u setup.py bdist_wheel"

artifacts:
  - path: dist
    name: code_beatrix
