environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install pymyinstall"
  - "%PYTHON%\\Scripts\\pymy_install3 pyproj cartopy cairocffi"
  #- "%PYTHON%\\Scripts\\pymy_install3 --set=pyquickhelper"
  #- "%PYTHON%\\Scripts\\pymy_install3 opencv_python fastrlock cffi scipy"
  #- "%PYTHON%\\python -c \"from pymyinstall.fix import fix_win32ctypes_core_cffi__advapi32_py;fix_win32ctypes_core_cffi__advapi32_py(fLOG=print)\""
  #- "%PYTHON%\\Scripts\\pymy_install3 cupy"
  #- "%PYTHON%\\Scripts\\pymy_install3 yaml scikit-image opencv-python"
  #- "%PYTHON%\\Scripts\\pymy_install3 protobuf shapely pyproj"
  #- "%PYTHON%\\Scripts\\pip install imageio imageio-ffmpeg"
  - "%PYTHON%\\Scripts\\pip install -r requirements_conda.txt"
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt"
  - "%PYTHON%\\Scripts\\pymy_install3 shapely"
  - set PYTHONPATH=src
  
build: off

test_script:
  - "%PYTHON%\\python -u setup.py unittests -g \".*((noenv)|(LONG)).*\""

after_test:
  - "%PYTHON%\\python -u setup.py bdist_wheel"

artifacts:
  - path: dist
    name: code_beatrix
