version: 2
jobs:
  build:
    docker:
      # pyproj does not work on Python 3.7 on linux
      - image: circleci/python:3.6.5
    
    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          - v2-dependencies-

      - run:
          name: Install pandoc
          command: |
                    sudo apt-get update 
                    wget https://github.com/jgm/pandoc/releases/download/2.2.1/pandoc-2.2.1-1-amd64.deb
                    sudo dpkg -i pandoc-2.2.1-1-amd64.deb
          
      - run:
          name: Install font
          command: |
                    sudo apt-get install -y libfreetype6-dev
          
      - run:
          name: Install tex
          command: |
                    sudo apt-get install -y texlive
                    sudo apt-get install -y texlive-latex-extra
                    sudo apt-get install -y texlive-lang-french
                    sudo apt-get install -y dvipng
          
      - run:
          name: Install 7z
          command: |
                    sudo apt-get install -y p7zip-full
          
      - run:
          name: Install InkScape
          command: |
                    sudo apt-get install -y inkscape
          
      - run:
          name: Install graphviz
          command: |
                    sudo apt-get install -y graphviz
          
      - run:
          name: Install ffmpeg
          command: |
                    sudo apt-get install -y ffmpeg
          
      - run:
          name: Install geos, proj for cartopy
          command: |
            sudo apt-get -qq update
            sudo apt-get install -y libproj-dev proj-bin proj-data
            sudo apt-get install -y python-pyproj
            sudo apt-get install -y libc6
            sudo apt-get install libgeos-dev
            sudo apt-get install python-gdal gdal-bin
            wget http://es.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj9_4.9.2-2_amd64.deb 
            sudo dpkg -i libproj9_4.9.2-2_amd64.deb 
            wget http://es.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj-dev_4.9.2-2_amd64.deb
            sudo dpkg -i libproj-dev_4.9.2-2_amd64.deb

      - run:
          name: install avconv (ffmpeg)
          command: |
                    sudo apt-get install libav-tools

      # pywavelets setup.py requires it
      - run:
          name: install numpy
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install numpy

      # cartopy setup.py requires it
      - run:
          name: install cython
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install cython

      - run:
          name: install dependencies (1)
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_conda.txt
            
      - run:
          name: install dependencies (2)
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            
      - run:
          name: install dependencies (3)
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install git+https://github.com/bokeh/datashader.git --upgrade --no-deps
            
      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py unittests -g ".*((noenv4_people)|(LONG)).*"

      - run:
          name: wheel
          command: |
            . venv/bin/activate
            python setup.py bdist_wheel
            mkdir -p test-reports/dist
            cp dist/*.whl test-reports/dist

      - run:
          name: documentation
          command: |
            . venv/bin/activate
            python setup.py build_sphinx
            
      - run:
          name: copy documentation
          command: |
            mkdir -p test-reports/doc
            zip -r -9  test-reports/doc/documentation_html.zip _doc/sphinxdoc/build/html
            mkdir -p test-reports/pdf
            cp _doc/sphinxdoc/build/elatex/*.pdf test-reports/pdf
            cp _doc/sphinxdoc/build/elatex/*.tex* test-reports/pdf
            
      - store_artifacts:
          path: test-reports
          destination: test-reports